// Relocation: plan keeps the layout relative to the dock, costs and takes days, old plant runs meanwhile, then swaps.
import * as G from '../src/sim/game.js';
import { links, inputPorts, ZONE, storageCapacity } from '../src/sim/floor.js';
import { defaultHatches, standardLayout } from '../src/sim/cells.js';
import { ok, done, hire as hireIn, chainPair, TEST_CITY } from './lib.mjs';
const { comp, prod } = chainPair();
const st = G.newGame({ seed: 'move', sandbox: true }); G.visitCity(st, TEST_CITY);
const lots = st.city.lots.filter(l => l.firm == null).sort((a, b) => a.sqft - b.sqft);
const small = lots.find(l => l.sqft >= 25000), big = lots[lots.length - 1];
G.rentBuilding(st, small.id); st.bank.checking += 2e6;
const hire = role => hireIn(st, role);
const A = G.placeEquipment(st, { kind: 'machine', family: comp.family, x: 2, y: 3, recipe: comp.id }).obj;
const B = G.placeEquipment(st, { kind: 'machine', family: prod.family, x: 10, y: 3, recipe: prod.id }).obj;
for (const o of [A, B]) for (const [x, y] of inputPorts(o)) st.floor.zones[y * st.floor.w + x] = ZONE.SAFETY;
const belt = G.connectByBelt(st, A.id, B.id); ok(belt.ok, 'belt laid in the old plant');
const draft = { family: 0, x: 15, y: 8, cw: 6, ch: 5, items: [] }; draft.hatches = defaultHatches(draft); draft.items = standardLayout(draft);
const C = G.buildCell(st, draft); ok(C.ok, 'cell built in the old plant: ' + (C.msg || ''));
const off = G.placeEquipment(st, { kind: 'office', officeType: 0, x: 10, y: 9 }); ok(off.ok, 'office placed: ' + (off.msg || ''));
hire('operator'); hire('operator'); hire('operator'); G.assign(st, st.employees[0].id, A.id); G.assign(st, st.employees[1].id, B.id); G.assign(st, st.employees[2].id, C.obj.id);
const feedsBefore = JSON.stringify(links(st.floor).feeds);
const plan = G.planMove(st, big.id);
ok(plan.ok, `plan to ${big.sqft} sq ft: ${plan.moved.length} items move, ${plan.dropped.length} left behind, ${plan.shifted.length} shifted, ${plan.days} days, cost ${plan.cost}`);
ok(plan.floor.w >= st.floor.w && plan.floor.h >= st.floor.h, `bigger floor ${st.floor.w}x${st.floor.h} -> ${plan.floor.w}x${plan.floor.h}`);
const cash0 = st.bank.checking;
const r = G.startMove(st, big.id); ok(r.ok, r.msg);
ok(cash0 - st.bank.checking >= plan.cost + big.rent - 1, 'moving cost and first month rent paid');
G.purchaseAll(st);
const madeBefore = A.produced;
G.advance(st, 1440 * 2);
ok(st.move && st.lotId === small.id && A.produced > madeBefore, `old plant keeps producing during the move (${A.produced - madeBefore} units), progress ${(G.moveProgress(st) * 100).toFixed(0)}%`);
G.advance(st, 1440 * (plan.days + 1));
ok(!st.move && st.lotId === big.id, 'move finished: now at the new building');
ok(st.floor.w === plan.floor.w && storageCapacity(st.floor) >= 40, `new floor in place (${st.floor.w}x${st.floor.h})`);
ok(JSON.stringify(links(st.floor).feeds) === feedsBefore, 'belt links survive the move: ' + JSON.stringify(links(st.floor).feeds));
ok(A.operator != null && st.employees.filter(e => e.assign === C.obj.id).length === 1, 'staff keep their machines and cell');
G.purchaseAll(st); const madeAfter = A.produced; G.advance(st, 1440 * 4); console.log('A status', A.status, 'inv', JSON.stringify(st.inventory).slice(0, 120));
ok(A.produced > madeAfter, 'production continues in the new plant');
ok(st.memos.some(m => /We have moved/.test(m.subject)), 'move memo sent');
// moving to a much smaller building leaves things behind or refuses on storage
const tiny = lots[0]; const p2 = G.planMove(st, tiny.id);
ok(!p2.ok || p2.dropped.length > 0 || p2.shifted.length > 0, `smaller building: ${p2.ok ? `${p2.dropped.length} dropped, ${p2.shifted.length} shifted` : p2.msg}`);
done('move');
